In [1]:
import pandas as pd
import requests

In [17]:
response= requests.get(r'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1') # this will show only page 1 but we have somewhere 8000
#response.json()
#{'page': 1,
# 'results': [{'adult': False,
#   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
#   'genre_ids': [12, 16, 10751, 14],
 #  'id': 1007757,
  # 'title': 'Swapped',
 #  'original_language': 'en',
  # 'original_title': 'Swapped',
   #'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   #'popularity': 101.6538,
   #'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   #'release_date': '2026-05-01',
   #'softcore': False,
   #'video': False,
   #'vote_average': 8.945,
   #'vote_count': 1860},

In [ ]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
df.head() # we want a particular key so we put it as results
# also we convert the data into a dataframe and select only the columns we want to keep.

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,101.6538,8.945,1860
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,163.6421,8.724,30689
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,219.5762,8.700,3287
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,42.0762,8.687,23112
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,157.6035,8.683,5660

In [9]:
df.shape

(20, 7)

In [14]:
temp_df=pd.DataFrame() #created empty dataframe contaning nothing
# we will add now all the movies from all the pages to this empty dataframe. We will use a for loop to do that.
movies=[]

In [ ]:
for i in range(1,429):
    response= requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    movies.extend(response.json()['results']) # we are extending the list of movies with the results of each page

In [18]:
temp_df = pd.DataFrame(movies)[
    ['id', 'title', 'overview', 'release_date',
     'popularity', 'vote_average', 'vote_count']
]

temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,101.6538,8.945,1860
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,163.6421,8.724,30689
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,219.5762,8.700,3287
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,42.0762,8.687,23112
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,157.6035,8.683,5660

In [19]:
temp_df.shape

(40, 7)